FROM kartoza/postgis:12.0


ENV POSTGRES_USER=postgres
ENV PGUSER=postgres
ENV POSTGRES_PASS=password
ENV PGPASSWORD=password
ENV POSTGRES_DBNAME=ictlife_infra_interview_may_2020
ENV PGDATABASE=ictlife_infra_interview_may_2020
ENV PGHOST=localhost
ENV ALLOW_IP_RANGE=0.0.0.0/0

VOLUME /var/lib/docker/volumes/pgdata:/var/lib/postgresql/12/main